---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8081}]
    - ["private_network", {ip: "192.168.56.11"}]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: sbeliakou/centos-7.3-x86_64-minimal

suites:
  - name: default
    run_list:
      - recipe[task1_community::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
